# Generated by Django 3.0.3 on 2020-02-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0003_auto_20200214_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_hash',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
